### ISSUE TITLE
Performance problems with CastXML and py++

### ISSUE THREAD

**Issue by iMichka** [gccxml/pygccxml#56]
The main effort was to make pygccxml and py++ work with CastXML. Now that this is done, one problem remains to be solved: performance. @mamoll reported that using py++ is now much slower than before.

When comparing the xml files (between gccxml and castxml), one thing which seems very different is for example the std namespace. All the internals are now exposed with CastXML. With gccxml std contained around 260 elements. With castxml it has more than 20000 … This is probably making pygccxml slow when parsing for declarations.

This will need to be benchmarked and tested. Probably we can just skip some of these declarations or re-order the dictionaries / lists to make the algorithm faster. I plan to do this for the 1.8.0 release.

**Comment by praetorian20** [comment]
I just ran into this a couple of days ago. A huge header that took about 90s to generate bindings in `-std=c++03` mode now takes 60m with `-std=c++14`. I've been tweaking things in pygccxml and have managed to get the time down to 25m (which is still not acceptable). I'll submit a PR with the changes once I get it down some more.

What was surprising was I saved about 10m by not calling `scopedef_t.init_optimizer` (which is supposed to optimize later queries). @mamoll If you get a chance, could you please try the same to verify you see a speed up too? To do this, add `optimize_queries=False` when you're calling the `module_builder.module_builder_t` constructor in pyplusplus.

**Comment by iMichka** [comment]
Hi. Thanks for reporting. I was also playing around with a profiler. Made already some slight changes.
I know about ```init_optimizer```; this is one of the first things that struck me when profiling.

I do not want to disable it completely. I think that we could disable the optimisers on the files that are not the files that are parsed (by looking at they location). But this is only the tip of the iceberg: there are multiple other places where pygccxml gets slow because of the number of declarations. Looping over arrays or dictionaries with more than 20000 elements, and that hundreds of time, si very slow.

We may need to have two declarations trees, one hight priority and the other one slow priority, to optimise lookup times. But this is an huge amount of work. Maybe there would be another nicer strategy, I am still thinking about this and experimenting.

This is just to let you know that I am also working on this. I may just allow to disable the optimisers optionally for 1.8.0, bring that release out, and work on real performance improvements later.

**Comment by mamoll** [comment]
Adding `optimize_queries=False` seems to have only a small effect in my case. The python binding runtime for my project is still "a good part of a day" with gcc5 (whereas with clang it's "a bit more than an hour").

**Comment by iMichka** [comment]
Looking at the Travis build (I know, this is not a perfect metric, but looking at the mean build time over multiple builds is not that bad), the test suite takes between 3 to 4 min to complete with gccxml. Using castxml with ```std=c++98``` and gcc 4, it's almost the same. The builds that take longer are the ones using ```std=c++11```; and even longer ```std=c++14``` (with gcc5) (8 to 9 minutes).

On my laptop, the test suite goes from 198s to 252s when using ```std=c++14``` wit castxml.

At first I was trying to optimise for ```std=c++98```, because I did not think about it. I will try to compare the time of each test, to see which are the ones which are taking the most time. This will hopefully allow to refine the testing process and setup a test case demonstrating the performance problems.

**Comment by praetorian20** [comment]
@mamoll Thanks for trying that out. What standard library implementation are you using with clang, libc++ or libstdc++? I'm curious whether this is a case of gcc being slow or if it's differences between the stdlibs.

@iMichka I'm happy to hear you're looking into this too. I haven't started rewriting any logic, all I've done so far is cached the results of some functions that were called repeatedly, and eliminated a few checks that were happening on each function call in some places.

It's likely further improvements will require some rewrites, so I'll make a PR out of what I have so far later today or tomorrow.

Not sure I understand what you mean about `init_optimizer`, I don't think you need to allow disabling it within pygccxml because it doesn't get called automatically (as far as I know). In my case, it was being called from pyplusplus, and I was able to disable that using the argument I mentioned above.

**Comment by mamoll** [comment]
@praetorian20 I am comparing clang + libc++ in the latest Xcode on El Cap with gcc5 + libstdc++ on Linux VMs. You could be right that the C++ std lib is the main culprit, not the compiler itself.

**Comment by iMichka** [comment]
@praetorian20 What I meant about the ```init_optimizer``` part is that we could probably be smart about when to use it: it should probably run on the declarations from the file you are parsing but not on the declarations defined in some ```std``` library files. Though I do not know if that is a good strategy. I am still worried that so many declarations are exposed. We may be able to optimise some bits, but at the end some methods still get called millions of times, which is expensive.

Here is a list of tests that run slower (in seconds). The comparison is between ```castxml + gcc6 + std=c++98``` and ```castxml + gcc6 + std=c++14```. I took all the tests that run for 1 second longer with ```std=c++14```. (The list is not sorted)

I am currently profiling these to see if any speed gain is possible.

```
declaration_files_tester.Test.test 1.42260813713
declarations_comparison_tester.Test.test_comparison_declaration_by_declaration 25.1094276905
declarations_comparison_tester.Test.test_comparison_from_reverse 8.47017979618
declarations_comparison_tester.Test.test_same_declarations_different_intances 8.55400776866
file_cache_tester.Test.test_from_file 8.92868590356
file_cache_tester.Test.test_update 2.37047886848
project_reader_correctness_tester.Test.test_correctness 17.9011819363
type_traits_tester.Test.test_has_any_non_copyconstructor 3.31692194939
core_tester.core_all_at_once_t.test_abstract_classes 1.57977294922
xmlfile_reader_tester.Test.test 11.0374550819
complex_types_tester.Test.test 1.91197180748
cached_source_file_tester.Test.test 2.7938029766
variable_matcher_tester.tester_2_t.test_no_defaults 2.90506100654
decl_printer_tester.Test.test_printer 3.15186810493
vector_traits_tester.Test.test_declaration 1.98915410042
dependencies_tester.Test.test_calldefs 2.78062915802
remove_template_defaults_tester.Test.test_deque 3.28198480606
find_container_traits_tester.Test.test_find_traits 11.1609299183
better_templates_matcher_tester.Test.test 2.21111297607
from_future_import_tester.Test.test_namespace_argument_int 2.53657603263
```

**Comment by iMichka** [comment]
I cached a bunch of things, and removed a function layer that added much overhead. There is a clear performance improvement. Running the test suite went down from 252s to 141s on my laptop, and some travis builders are now faster.

Of course this does not mean that pyplusplus will be faster, I did not test this in a real-life context.

Still, the performance is not as good as when using gccxml or using the ```std=c++98``` flag. There is still room for improvement.
- I can cache more things; but I am afraid that RAM usage will increase a lot.
- Each declaration has it's own cache. I think it would be more performant to have a single cache object for all the declarations. Maybe I could write something like an LRU cache, but I need to benchmark that first. Not sure if this is the right caching strategy (maybe there are others that may work better here).
- Of course more profiling needs to be done, but it is very time-consuming to find out what is going on.

**Another important thing**: I just read a comment in the pyplusplus code:

```
  To speed up your generation process you might want to consider making the
  declaration tree as small as possible and only store those declarations that
  somehow have an influence on the bindings. Ideally, this is done as early
  as possible and luckily gccxml provides an option that allows you to reduce
  the number of declarations that it will store in the output XML file. You can
  specify one or more declarations using the ``-fxml-start`` option and only
  those sub-tree starting at the specified declarations will be written. For
  example, if you specify the name of a particular class, only this class
  and all its members will get written. Or if your project already uses
  a dedicated namespace you can simply use this namespace as a starting point
  and all declarations stemming from system headers will be ignored (except
  for those declarations that are actually used within your library).

  In the ``pygccxml`` package you can set the value for the ``-fxml-start``
  option using the ``start_with_declarations`` attribute of the
  ``pygccxml.parser.config_t`` object that you are passing to the parser.
```

This option also works for castxml. I think ompl is not using the ```start_with_declarations``` option. This will definitively speed things up. Could you test this ?

**Comment by mamoll** [comment]
The `start_with_declarations` option speeds things up significantly! Module generation time went down from 3-4 hours per module to about 30 minutes per module. I need to do some more testing to see if there are any significant differences in generated code, but this seems extremely promising. I used pygccxml 1.7.6, so the timing results do not include your other performance improvements yet.

**Comment by mamoll** [comment]
The code generator is still running on my Linux VM, but one module that used to take 12700 seconds now takes 12400 seconds. I don't expect a big improvement in the other modules either. In short, it seems to help a bit, but not as much as you'd expect. I'll run it again with the latest revision of pygccxml to see if that makes a difference.

**Comment by praetorian20** [comment]
I just submitted PR #59 with the changes I have.

Unfortunately, `-fxml-start` is not an option for me because the code I've been using to benchmark is first auto-generated from some XML files and then we generate Python bindings. The generated classes all have a common name prefix instead of a namespace. And since classes can be added to by someone modifying XML, it's too tedious to maintain a list of names.

The biggest bottleneck for me right now is 326 million calls to `hierarchy_info_t.__eq__`, all of which are from within `project_reader_t._join_class_hierarchy`. Rewriting `_join_class_hierarchy` to avoid all those calls could possibly improve things, but I haven't spent the time to understand what exactly that function is doing.

**Comment by iMichka** [comment]
@praetorian20 I merged your pull request. Thanks again.
326 millions of calls is quite huge. Even optimising the function would probably not help, the overhead of calling methods/functions so many times is just huge. The best thing would be to find a smart way not to make all these calls. I'll have a look to ```project_reader_t._join_class_hierarchy```. Also, I tried only to optimise the pygccxml side, but there may also be some improvements that could be done in pyplusplus. I did not profile that part of the code.

@mamoll Too bad the ```start_with_declarations``` does not help. This is surprising as it should really reduce the number of declarations to parse. Please test the newest version of pygccxml. Note that I deprecated some functions/attributes, but the warning should propose you an alternative. This was mainly done for performance reasons. There were a lot of cyclic imports which I needed to break, but that required deprecating some stuff. A new version of pyplusplus will be needed in the future supporting the new API. Still, you can ignore the warnings the time being.

**Comment by mamoll** [comment]
I updated pyplusplus to use the new pygccxml API. I tested the latest development version of both with ompl on OS X with clang and there seem to be significant performance improvements. Nice!

There are some pyplusplus tests that are still failing. Some fail with this error, which might be a bug in pygccxml:
```
...
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pygccxml/declarations/other_traits.py", line 74, in value_type
    return internal_type_traits.get_by_name(type_, "value_type")
 File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pygccxml/declarations/other_traits.py", line 19, in get_by_name
    if class_declaration_traits.class_traits.is_my_case(type_):
AttributeError: 'declaration_xxx_traits' object has no attribute 'class_traits'
```

**Comment by iMichka** [comment]
Commit d50a4790b5209eda26018045362b5999d44d5f91 should take care of the error you got. This method is not tested at all, so that the error slipped through when I did the refactoring.

I would be interested on how fast we are now. I would like to get 1.8.0 out soon, there have been many changes. There is no hurry but if performance is somewhat better, that would be a first step. A second round of performance improvements can be done for 1.9.0.

I hope the changes in the pygccxml were not too complicated to fix. I tried to document the changes as good as possible. The changes were really necessary for the performance. There were at least 5 to 10 imports done inside methods (to prevent cyclic imports); if that method got called thousands of time the import lookup would slow down the processing.

**Comment by mamoll** [comment]
I ran a comparison of the latest pygccxml / pyplusplus release vs latest commit of both on an Ubuntu 14.04 machine with g++5. The module generation time for the first three python modules in OMPL changed  from:
```
35.87
588.83
16186.28
```
to:
```
22.48
491.60
14803.08
```
(all times in seconds). All in all, a significant improvement. In both cases I use the `start_with_declarations` parameter for the `module_builder_t`. Perhaps the potential benefit of this is lost when I do something like this?:
```
self.std_ns = self.mb.namespace('std')
```
(Here, `mb` is of type `module_builder_t`.) I think I need to take a closer look at my own code. It's quite possible that I use pygccxml /  pyplusplus in a horribly inefficient way.

**Comment by iMichka** [comment]
Yes, looking at the 'std' namespace is really expensive since CastXML. The most declarations are in there and slow down the parsing a lot. Using `start_with_declaration` and then still looking at the content of `std` is probably not helping.

I just tried to optimise pygccxml alone, without looking at pyplusplus. This means that there is probably some optimisation to do there too.

The only two lines I have been using for benchmarking is:
```
python -m cProfile -o profile_data.pyprof script_to_profile.py
pyprof2calltree -i profile_data.pyprof -k
```

(you can install pyprof2calltree with pip). Playing around with the profiler helped a lot. Probably we need to do the same in a real-world case (I mean, run it on some pyplusplus calls). I'll run it maybe on 2-3 examples, maybe some bigger bottlenecks can then be removed.

**Comment by mamoll** [comment]
I created some profile data for [OMPL](http://github.com/ompl/ompl) using the latest pygccxml and pyplusplus; see https://www.dropbox.com/sh/1mpjelmm51knw4b/AACXvaeyRv_75RLer2MO7Q_ka?dl=0. I looked at it, but I don't see an obvious way to improve performance.

**Comment by iMichka** [comment]
Thanks for the files. There are probably still some small things that can be optimised, but the most time is taken by ```__find_in_registry```, ```__find_row_in_registry``` and especially ```does_refer_same_decl```. Some of the profile files show that ```does_refer_same_decl``` is called around 5 billion of times ! Even if the comparison in there is fast, the overhead of calling the method is huge.

One trick we coud do is to not call ```does_refer_same_decl``` by adding the ```key```, ```signature``` and ```normalized_name``` comparison directly in ```__find_row_in_registry```. That would probably remove the method call overhead. Not sure how much it would help but it can't make it worse.

```
    def __find_row_in_registry( self, row ):
        try:
            decls = [rrow for rrow in self.__registry[ row.key ][ row.normalized_name ] if (rrow.key == row.key and rrow.signature == row.signature and rrow.normalized_name == row.normalized_name)]
            if decls:
                return decls[0]
            else:
                return None
        except KeyError:
            return None
```

Another thing that we could try is to sort the rows before looping over them. We should implement the ```__lt__``` method and sort by declaration.location. By putting the file you are parsing first, it could be that the right declarations are found first. All the declarations in std and others would come later in the list of declarations. Other more refined sorting strategies could also be made (maybe in pygccxml directly).

All this are just hypotheses. I will have some time in 2 days to look at this in detail. You can already try my first idea if you want.

**Comment by iMichka** [comment]
Disregard my second comment about the sorting, it seems all the rows are parsed anyway, so sorting will not help. But this is weird. If a declaration is found, it can be returned directly without looping over all the rows. Maybe writing a normal for loop and adding a break when the condition is met would help ?

**Comment by mamoll** [comment]
Good catch. Using` next()` appears to be preferred way to find the first occurrence in a list/iterator. This seems to speed things up quite a bit. [I committed a fix in pyplusplus.](https://bitbucket.org/ompl/pyplusplus/commits/ef389e66ba3bf9ccd878edd57c7df694ff53ef76). I'll have to look more carefully to see if there's more low-hanging fruit like this.

**Comment by iMichka** [comment]
Cool use of ```next```, I did not think about that strategy. Next week I will look if I find time to run more benchmarks with pyplusplus.

I will be on holidays in August. Hacking around will probably slow down, so I plan to release 1.8.0 during September. This leaves some time for you if you want to look for more bottlenecks. I do not plan to make any API change until then, so the current state is frozen.

**Comment by mamoll** [comment]
Sounds good. The registry related calls seem to dominate everything else in pyplusplus. I suspect that the start_with_declarations is actually ignored for multi-module code generation (which is what I am doing). That would explain why the registries are so large and why it takes forever to iterate through them.

**Comment by praetorian20** [comment]
@mamoll Your last comment prompted me to run a test where I attempted to turn off multi-module code generation, but not sure I did it right because I still see pyplusplus generating multiple `*.pypp.{h,c}pp` files.

I passed `compilation_mode=pygccxml.parser.COMPILATION_MODE.ALL_AT_ONCE` to the `module_builder_t` constructor. Whatever that's doing, it improves things a lot in my case. Generation time went down from 1400s to 700s with that change (I'm using the latest development versions of both pyplusplus and pygccxml).

**Comment by mamoll** [comment]
@praetorian20 It still generates a file per class. All the `*.pypp.{h,c}pp` files still need to be compiled into a module.

I wasn't aware of the `compilation_mode=pygccxml.parser.COMPILATION_MODE.ALL_AT_ONCE` flag. In my own code I already [combine all header files into one header in a preprocessing stage]( https://github.com/ompl/ompl/blob/master/CMakeModules/PythonBindingsUtils.cmake#L38). This made a huge difference at the time (with gccxml and older versions of gcc/clang). Turning on this flag still results in some small improvement, so even with just one header it seems like a good idea. The only catch is that memory usage will go up quite a bit.

**Comment by iMichka** [comment]
I made a FAQ entry with some of the things we discovered: http://pygccxml.readthedocs.io/en/develop/faq.html#performance

Performance has been improved for 1.8.0. I will continue to play around with the profiler later, but the first goal was achieved. I am still not happy with time it takes to run the test suite when using castxml compared to gccxml, especially with gcc5.

I'm am closing this bug now, there is no need to keep it open. Thanks to you two for having helped out on that topic.

**Comment by letuantang** [comment]
> I updated pyplusplus to use the new pygccxml API. I tested the latest development version of both with ompl on OS X with clang and there seem to be significant performance improvements. Nice!
> 
> There are some pyplusplus tests that are still failing. Some fail with this error, which might be a bug in pygccxml:
> 
> ```
> ...
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pygccxml/declarations/other_traits.py", line 74, in value_type
>     return internal_type_traits.get_by_name(type_, "value_type")
>  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pygccxml/declarations/other_traits.py", line 19, in get_by_name
>     if class_declaration_traits.class_traits.is_my_case(type_):
> AttributeError: 'declaration_xxx_traits' object has no attribute 'class_traits'
> ```

Dear Mr. Mark Moll,
I got the same problem during the process to wrap the code from C++ to python. Can you give me a hint on how to solve it? Thank you so much.
